### ISSUE TITLE
Ideas for App - For Review

### ISSUE THREAD

**Issue by LfifteenA** [CodingForProduct/tap_rewards#4]
![screen shot 2017-06-30 at 12 40 47 am](https://user-images.githubusercontent.com/24921963/27725849-06e0f1a4-5d2d-11e7-9517-765f64cad5e9.png)
![screen shot 2017-06-30 at 12 40 55 am](https://user-images.githubusercontent.com/24921963/27725850-06e3a37c-5d2d-11e7-8ca2-6e1930f6857a.png)
![screen shot 2017-06-30 at 12 41 02 am](https://user-images.githubusercontent.com/24921963/27725851-06e7a850-5d2d-11e7-9bd7-68090dc4ab43.png)

**Comment by carolinambravo** [comment]
Looks awesome!

**Comment by LfifteenA** [comment]
We reviewed on teleconference - no longer needed here
